### ISSUE TITLE
Consider making Pac4jFactory easier to extend

### ISSUE THREAD

**Issue by wardr** [pac4j/dropwizard-pac4j#14]
Currently Pac4jFactory is difficult to work with if you need to override things:

1) the run() method is final, so you cannot extend the class to do additional (or different) configuration 

2) All collections used in this class  are immutable  which means you can't modify things later, such as adding clients or matchers,

That said, I fully acknowledge that doing these things might be abusing this bundle and that there may be better ways to do more customized/advanced configuration.

In my case I do this because 

* When trying to learn pac4j, it's easier and more flexible when you do the configuration in code (e.g. type-checking)

* In my apps, authentication changes rarely and is configured the same way in dev and in production, so it might as well be in code.

**Comment by victornoel** [comment]
Actually, I have the same needs than you (the configuration not changing), but I started by implementing the dropwizard integration with the general dw ways of doing things.

So this is a really good starting point for improving this lib, I will think about that and make some propositions here :)

**Comment by victornoel** [comment]
@wardr Actually, if your objective is just to modify pac4j configuration after the bundle has done its work, it is meant to be easy: just access the `Config` object via `getConfig()` on `Pac4jBundle`.

I usually organise my application like this:
```java
public class MyApplication extends Application<C> {

    public final Pac4jBundle<C> pac4j = new Pac4jBundle<C>() {
        @Nullable
        @Override
        public Pac4jFactory getPac4jFactory(C configuration) {
            return configuration.getPac4jFactory();
        }
    };

    @Override
    public void initialize(Bootstrap<C> bootstrap) {
        bootstrap.addBundle(pac4j);
    }

    @Override
    public void run(C configuration, Environment environment) throws Exception {
        pac4j.getConfig().doSomethingOnItBecauseItIsCompletelyMutable();
    }
}
```

Maybe this is actually enough to solve ALL your needs?
But there will still needs to make some changes in some places maybe even with that? Could you try to follow this pattern and tell me what is missing then?

**Comment by wardr** [comment]
I tried it again, and confirmed that I indeed can't change things the way I need to. For example, configuring it in the Application class as below causes it to throw an exception when attempting to add a matcher, because the set the matchers are in is immutable. 

Example set-up:

```
    private final Pac4jBundle<DemoConfiguration> securityBundle = new Pac4jBundle<DemoConfiguration>() {
        @Nullable
        @Override
        public Pac4jFactory getPac4jFactory(DemoConfiguration configuration) {
            return configuration.getPac4jFactory();
        }
    };

    ...
    
    @Override
    public void run(DemoConfiguration config, Environment env) throws Exception
    {
        configureSecurity(env);
        ...
    }

    private void configureSecurity(Environment environment)
    {
        // Dropwizard does not enable sessions by default, so add a session handler
        MutableServletContextHandler contextHandler = environment.getApplicationContext();
        contextHandler.setSessionHandler(new SessionHandler());

        // pac4j configuration

        Config config = securityBundle.getConfig();
        config.setSessionStore(new ServletSessionStore());
        environment.jersey().register(new ServletJaxRsContextFactoryProvider(config));
        environment.jersey().register(new Pac4JSecurityFeature(config));
        environment.jersey().register(new Pac4JValueFactoryProvider.Binder());

        // require authentication everywhere, except for whitelisted paths

        final String matcherName = "authPathMatcher";
        UrlPathMatcher matcher = new UrlPathMatcher();
        matcher.addExcludedPath("/");
        matcher.addExcludedPath("/login");
        matcher.addExcludedPath("/callback");
        config.addMatcher(matcherName, matcher);

        environment.jersey()
                .register(new Pac4JSecurityFilterFeature(config, null,
                        "isAuthenticated", null,
                        "authPathMatcher", null));

        JooqAuthenticator authenticator = new JooqAuthenticator(dbBundle.getConfiguration());
        FormClient formClient = new FormClient("/login", authenticator);
        formClient.setCallbackUrl("/callback");

        Clients clients = new Clients(formClient);
        clients.setCallbackUrlResolver(new JaxRsCallbackUrlResolver());
        config.setClients(clients);

        // TODO: Authorization
    }
```

**Comment by victornoel** [comment]
@wardr ok! I finally got your point, sorry for being so thick, I didn't get what you meant :P

As for the `final` modifier on `Pac4jBundle.run(T, Environment)`, I could remove it, but I'm not sure you would be able to do anything useful with it, what is the use case exactly there?
I think if you don't want pac4j to be registered at all, you simply need to have `Pac4jFactory getPac4jFactory(T configuration)` return `null`, if you want pac4j to be setup but want to take care of the `Config` yourself, then you simply return an empty ` new Pac4jFactory()` (and don't put in in your application config) and then modify it in your application run method (now that the collections are mutable).

What do you think? Any other area of improvement for your needs?

**Comment by victornoel** [comment]
Concerning `Pac4jBundle.run()` what do you think if the logic in it was extracted in another method that could be overridden and that is called AFTER the `Pac4jFactory` has built the `Config`?
Like this one can modify the `Config` at that point and not wait for the `Application.run` method being executed.
And one can modify it before calling the super implementation of the method, so that it can be influenced by user code...

**Comment by victornoel** [comment]
Hm, or simply have a method that can be overridden to manipulate the config before the environment is modified?
Like this you can either customize the factory programmatically from within `getPac4jFactory` and customize the `Config` from within this new method.
It could be called `getPac4jConfig` for example, and take the built `Config` from the factory as well as the `Application`'s `Configuration`?

These are some ideas for brainstorming :)

**Comment by victornoel** [comment]
After some experiments, I don't really see the need for making those customizations possible... it complexifies things more than making them clearer. Any specific use case that would justify introducing them?

**Comment by wardr** [comment]
I agree with you - just making the applicable collections immutable is all that is needed.
