### ISSUE TITLE
Provide a way to define how JAX-RS Filters are created

### ISSUE THREAD

**Issue by victornoel** [pac4j/dropwizard-pac4j#19]
In order to cover use cases such as pac4j/pac4j#700 or pac4j/jax-rs-pac4j#13, it would be great to have a way to specify how the filters are created.

Like this, the user can decide to modify the filter using the setters to change the logic or use an extension of the filter to redefine pac4j's behaviour.

Note that the objective is not to be able to modify filters for a given annotation or configuration, but more to do it in a general way. If one needs one specific filter on top of the normal ones, then it is better to register it in Jersey by hand.

**Comment by leleuj** [comment]
Let's use the `SecurityLogic` (and the `CallbackLogic`) from the `Config` if you agree.

**Comment by victornoel** [comment]
hehe, we are going around inbetween issues, see my last comment on pac4j/jax-rs-pac4j#13: I also need to accept extension of the filter itself… (for the `HttpActionAdapter`)

Or I could make the HttpActionAdapter customizable via a setter on the filter and add a way to specify it in the dropwizard configuration!
If I have the three logics in the Config, I can do that :)

**Comment by leleuj** [comment]
Guess what, the `HttpActionAdapter` can be defined in the `Config` as well: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/config/Config.java#L151

We're in line: let's add the `CallbackLogic` and `LogoutLogic` in the `Config` first: https://github.com/pac4j/pac4j/issues/810

**Comment by victornoel** [comment]
Is that new? I didn't take advantage of it before I think…

All of this would go in the pac4j 2.0 version of the jax-rs-pac4j and dropwizard-pac4j, because that's too much breaking changes I think.

**Comment by victornoel** [comment]
Closed in favour of pac4j/jax-rs-pac4j#14, pac4j/jax-rs-pac4j#15, pac4j/dropwizard-pac4j#20 and pac4j/dropwizard-pac4j#21.

**Comment by leleuj** [comment]
Both the `SecurityLogic` and `HttpActionAdapter` existed in 1.9.x and we could add the new logics to the 1.9.6-SNAPSHOT version if you need them.

**Comment by victornoel** [comment]
hmmm, but is adding the logics in a minor release ok? That's a bit of a functionality/behaviour change if something becomes customizable?

But yeah, if you do it, I will follow and fix these issues in a 1.2.x release of jax-rs-pac4j and dropwizard-pac4j!

**Comment by leleuj** [comment]
As soon as it doesn't break anything, I think it's acceptable, not in the semver way nonetheless. Will do.
