### ISSUE TITLE
disable authentication globally?

### ISSUE THREAD

**Issue by ngton** [pac4j/dropwizard-pac4j#24]
Is there any way I can disable authentication globally for the dropwizard service? 

I have multiple deployment scenarios and I really need to be able to configure whether authentication is enabled in the dropwizard yml config.

I have tried to use a excludePath: ^(.*)$ but every class/method that has an annotation, eg

@Pac4JSecurity(clients="DirectBasicAuthClient" ,authorizers = "isAuthenticated")

still requires authentication.

Thanks

**Comment by victornoel** [comment]
The best way to disable pac4j is simply to have `Pac4jBundle.getPac4jFactory(T)` (that you should be overriding when setting up the bundle) to return `null`.

If that answers your question, please close the issue, or we will look together at ways to solve your problem :)

**Comment by ngton** [comment]
Thanks for the quick response. That works perfectly.
