### ISSUE TITLE
Shouldn't we check the default client at the pac4j core level

### ISSUE THREAD

**Issue by leleuj** [pac4j/dropwizard-pac4j#26]
I see that you check if the default client is part of the clients: https://github.com/pac4j/dropwizard-pac4j/blob/master/src/main/java/org/pac4j/dropwizard/Pac4jFactory.java#L326

Shouldn't we check this in the Clients component directly?

**Comment by victornoel** [comment]
I'm not sure I understand the problem.

To rephrase what is happening in this code: the user choose a default client (to be set as the `Clients.getDefaultClient()`) but he can only do so with a `String` in the YAML and `Clients` expects a `Client`. So we simply find the corresponding client from all the clients declared in the YAML file.

Do you mean it would be best to use `Clients.getClients` instead of `clients`? For now it would be exactly the same I think, no?

**Comment by leleuj** [comment]
No, I think about the check that the default client is one of the defined clients (otherwise, you can't set it).

**Comment by victornoel** [comment]
Sorry ^^ I still don't get your point, I'm a bit slow this morning :)
What could we do instead of what we are currently doing?

**Comment by leleuj** [comment]
No problem. Let's take an example. I have the `FacebookClient` and the `FormClient` defined in the `Clients`.
Let's say that I want to add the `SAML2Client` as a default client, it won't complain.
So my idea is to check that the `SAML2Client` is already one of the defined clients (`FacebookClient`,  `FormClient`)  which is false in that case.

Is it clearer?

**Comment by victornoel** [comment]
Isn't that what is already happening with this code?

This would be trigerred:
```java
            if (!found) {
                throw new IllegalArgumentException("Client '" + defaultClient
                        + "' is not one of the configured clients");
            }
```

**Comment by leleuj** [comment]
Sure, but it's in the Dropwizard source code: shouldn't we move that to the pac4j-core module, in the `Clients` class, at the `setDefaultClient` level?

**Comment by victornoel** [comment]
aaah, yes, ok, that's a good idea! sorry for the confusion :)

**Comment by leleuj** [comment]
Tracked here: https://github.com/pac4j/pac4j/issues/870

**Comment by leleuj** [comment]
Done and addressed in: https://github.com/pac4j/dropwizard-pac4j/pull/28 also...
