### ISSUE TITLE
Why do you choose Dropwizard

### ISSUE THREAD

**Issue by HelloTo4x** [pac4j/dropwizard-pac4j#297]
Hi, i am reading your repository and i am interested in this, but i have a question, you use Dropwizard to achieve high concurrency in Java, is it correct ? Why don't u choose others like Netty or Reactive Programming ? Can you tell me the purpose of Dropwizard in your project, and the pros and cons of Dropwizard, thank u so much

**Comment by leleuj** [comment]
pac4j (https://github.com/pac4j/pac4j) is a Java security engine used in many frameworks. Dropwizard is only one of the many frameworks available: https://www.pac4j.org/implementations.html
Every framework has its pros and cons.
