### ISSUE TITLE
dropwizard-pac4j-demo?

### ISSUE THREAD

**Issue by leleuj** [pac4j/dropwizard-pac4j#3]
Almost all pac4j implementations have a demo to demonstrate its features. It would great to have a `dropwizard-pac4j-demo` for this bundle.

**Comment by victornoel** [comment]
FYI @leleuj, we plan with @wardr to integrate its demo application into the official one since it covers more functionalities :)

**Comment by leleuj** [comment]
Sounds good to me

**Comment by mohit28081985** [comment]
ASDASD

**Comment by leleuj** [comment]
See: https://github.com/pac4j/dropwizard-pac4j-demo
