### ISSUE TITLE
Stateless session handling?

### ISSUE THREAD

**Issue by htamas** [pac4j/dropwizard-pac4j#32]
I have been trying to set up a Google OpenID Client login to my small webapp, but we are running multiple instances of the same application.

Are there any suggestions how am I supposed to do session handling in this case? I was thinking about storing the whole session in a cookie, so nothing is stored on server side, but I don't know how should I approach this.

Have anyone had some experiences similar to this?

**Comment by victornoel** [comment]
@htamas it would be better to discuss this directly in pac4j-user: http://www.pac4j.org/mailing-lists.html

Your question is not really related to the dropwizard integration of pac4j (and I personally I'm not sure I can help ^^).

Thanks!
