### ISSUE TITLE
saml.keyStoreAlias seems to be ignored

### ISSUE THREAD

**Issue by NMichas** [pac4j/dropwizard-pac4j#35]
Version: 2.0.0

It seems the configuration-defined alias for the SP keystore key is ignored. Config yaml extract:

```
pac4j:
  callbackUrl: /callback
  clientsProperties:
    ... other entries here ...
    saml.keyStoreAlias: dev123
```

But when the keystore is generated, I see in the logs:

```
WARN  [2017-10-08 16:02:03,583] org.pac4j.saml.client.SAML2ClientConfiguration: Provided keystoreResource does not exist. Creating one for: file [/XXXXXXXX.jks]
WARN  [2017-10-08 16:02:03,662] org.pac4j.saml.client.SAML2ClientConfiguration: Using keystore alias SAML2ClientConfiguration
WARN  [2017-10-08 16:02:03,662] org.pac4j.saml.client.SAML2ClientConfiguration: Using keystore type jks
INFO  [2017-10-08 16:02:04,340] org.pac4j.saml.client.SAML2ClientConfiguration: Created XXXXXXX.jks with key alias saml2clientconfiguration
```

And, indeed, inspecting the generated keystore there is a key with alias `saml2clientconfiguration` created.

Is there maybe some other way to set the alias of the key or is this a bug?

**Comment by victornoel** [comment]
@NMichas I think this is an issue for pac4j-config, would you mind opening an issue in the main pac4j repository and close this one?
Thanks :)

Could you also include the complete configuration (except for passwords ;) in the issue?

**Comment by NMichas** [comment]
Re-opened at https://github.com/pac4j/pac4j/issues/1008
