### ISSUE TITLE
Publishing 3.0-RC1

### ISSUE THREAD

**Issue by j-martin** [pac4j/dropwizard-pac4j#40]
@victornoel would it possible to publish dropwizard-pac4j and jax-rs-pac4j?

Alternatively is there a timeline on when they will be published?

Thanks,

JM

**Comment by victornoel** [comment]
@j-martin yes, it will happen very soon. We have some open problems and must decide what to do, but it will be released before next week I suppose :)
I will keep this open in the meantime!

**Comment by leleuj** [comment]
OK. You're right.

**Comment by victornoel** [comment]
@leleuj if you are ok, I think we should release right now:
 - jax-rs-pac4j 3.0.0-RC1 as well as 2.2.0 while we are at it (see [changes](https://github.com/pac4j/jax-rs-pac4j/wiki/Release-notes))
 - dropwizard-pac4j 3.0.0-RC1 as well as 2.2.0 while we are at it (see [changes](https://github.com/pac4j/dropwizard-pac4j/wiki/Release-notes))

**Comment by leleuj** [comment]
OK. I'll take care of that ASAP. I'll keep you posted.

**Comment by j-martin** [comment]
Merci!

**Comment by leleuj** [comment]
@victornoel I see a pending pull request on jax-rs-pac4j: https://github.com/pac4j/jax-rs-pac4j/pull/42, should I really cut the releases?

**Comment by leleuj** [comment]
It doesn't take much time to release, so let's do that now.

**Comment by leleuj** [comment]
One more thing: for jax-rs-pac4j, the version should be 3.0.0-RC1-SNAPSHOT and not 3.0.0-SNAPSHOT...

**Comment by leleuj** [comment]
We're in line, but currently, jax-rs-pac4j (master) is at 3.0.0-SNAPSHOT (https://github.com/pac4j/jax-rs-pac4j/blob/master/pom.xml#L16) which would be released as 3.0.0 by default. Anyway, I'll handle that...

**Comment by victornoel** [comment]
Nope: only those meant to be used by users (the "public" ones) are under
org.pac4j.
The others are internal to the jax-rs integration.
Another choice would have been to prefix all"internal" ones with "jax-rs-"
but I feel like it would have made things less clear for users.

Thanks :)

Le ven. 27 avr. 2018 à 08:24, LELEU Jérôme <notifications@github.com> a
écrit :

**Comment by leleuj** [comment]
OK. I understand. It makes sense. It's hard to have a good solution for "private" artifacts, this one is ok. I just finished releasing dropwizard-pac4j v3.0.0-RC1, it will be available in the Maven central repository in a few hours. Like the others which are already there.
