### ISSUE TITLE
Cannot inject "Pac4jProfile" in a "@ScopedRequest" ressource

### ISSUE THREAD

**Issue by psouquet** [pac4j/dropwizard-pac4j#46]
Upgrading **Pac4j** from **v2.1.0** (either to **v2.3.0** or **v3.x.x**), you can no longer inject a profile into a `@RequestScoped` ressource constructor like this:
```java
@Path("/myressource")
@RequestScoped
public class MyResource {

    @Inject
    public BreakerResource(@Pac4JProfile final CommonProfile profile) {
    }
}
```
This results in a runtime error while accessing the ressource (even after a successful login with an `IndirectBasicAuthClient`):
```
DEBUG [2019-03-19 13:15:33,674] org.pac4j.jax.rs.jersey.features.Pac4JValueFactoryProvider: Cannot inject a Pac4j profile into an unauthenticated request, responding with 401
```

Replacing `@Pac4JProfile` with a `@Pac4JProfileManager` works fine though. And you can still inject a `@Pac4JProfile` in `@Singleton` ressources as well.   

Observed with **dropwizard v1.3.0** and **v1.3.8.**
Here's a link to the full [group discussion](https://groups.google.com/forum/#!topic/pac4j-users/6ZSw4dsPsBY).
An one to the [bug reproduced in dropwizard-pac4j-demo](https://github.com/psouquet/dropwizard-pac4j-demo/tree/breaking-demo).

**Comment by leleuj** [comment]
To be re-tested after the upgrade to pac4j v4.
