### ISSUE TITLE
excludePath example uses deprecated class

### ISSUE THREAD

**Issue by ngton** [pac4j/dropwizard-pac4j#47]
The documentation here https://github.com/pac4j/dropwizard-pac4j says

 matchers:
    # this let the /user/session url be handled by the annotations
    excludeUserSession:
      class: org.pac4j.core.matching.ExcludedPathMatcher

But org.pac4j.core.matching.ExcludedPathMatcher is deprecated and results in a no class found:

caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'org.pac4j.core.matching.ExcludedPathMatcher' as a subtype of [simple type, class org.pac4j.core.matching.Matcher]: no such class found

**Comment by leleuj** [comment]
It's now called `PathMatcher`.
